name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
    name: docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-06-22

      - name: Update apt repositories
        run: sudo apt update

      - name: Setup DVC
        uses: iterative/setup-dvc@v1

      - name: Fetch Fixtures
        run: dvc pull

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
            target/debug
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build documentation
        run: cargo doc --release --no-deps
      - name: Publish documentation
        run: |
          cd target/doc
          git init
          echo '<meta http-equiv="refresh" content="0; url=https://webb-tools.github.io/protocol-substrate/pallet_vanchor/index.html">' > index.html
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy documentation ðŸš€'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages